import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { getSessionUser } from "@/lib/auth";
import { pool } from "@/lib/db";

const fields = "c.id,c.name,c.color,c.owner_user_id,c.visible,c.type,c.created_at";
function view(row: Record<string, unknown>) { return { id: String(row.id), name: String(row.name), color: String(row.color), ownerUserId: String(row.owner_user_id ?? ""), visible: Boolean(row.visible), type: String(row.type), createdAt: String(row.created_at), viewerUserIds: Array.isArray(row.viewer_user_ids) ? row.viewer_user_ids.map(String) : [] }; }
async function ensurePersonalCalendar(userId: string) { const existing = await pool.query("SELECT id FROM calendars WHERE owner_user_id=$1 LIMIT 1", [userId]); if (existing.rows[0]) return; const id = randomUUID(); await pool.query("INSERT INTO calendars (id,name,color,owner_user_id,visible,type) VALUES ($1,'Lịch cá nhân','#6366f1',$2,TRUE,'personal')", [id, userId]); await pool.query("INSERT INTO calendar_users (calendar_id,user_id,permission) VALUES ($1,$2,'edit') ON CONFLICT DO NOTHING", [id, userId]); }
async function canEdit(userId: string, role: string, calendarId: string) { if (role === "full_access") return true; return Boolean((await pool.query("SELECT 1 FROM calendars c LEFT JOIN calendar_users cu ON cu.calendar_id=c.id AND cu.user_id=$2 WHERE c.id=$1 AND (c.owner_user_id=$2 OR cu.permission='edit')", [calendarId, userId])).rows[0]); }
async function syncUsers(calendarId: string, ownerId: string, userIds: string[]) { await pool.query("DELETE FROM calendar_users WHERE calendar_id=$1", [calendarId]); for (const userId of [...new Set([ownerId, ...userIds].filter(Boolean))]) await pool.query("INSERT INTO calendar_users (calendar_id,user_id,permission) VALUES ($1,$2,$3)", [calendarId, userId, userId === ownerId ? "edit" : "view"]); }
export async function GET() { try { const actor = await getSessionUser(); if (!actor) return NextResponse.json({ ok:false,error:"Chưa đăng nhập." },{status:401}); await ensurePersonalCalendar(actor.id); const where = actor.role === "full_access" ? "" : "WHERE c.owner_user_id=$1 OR EXISTS (SELECT 1 FROM calendar_users access WHERE access.calendar_id=c.id AND access.user_id=$1)"; const result = await pool.query(`SELECT ${fields},ARRAY_REMOVE(ARRAY_AGG(DISTINCT cu.user_id),NULL) viewer_user_ids FROM calendars c LEFT JOIN calendar_users cu ON cu.calendar_id=c.id ${where} GROUP BY c.id ORDER BY c.created_at,c.name`, actor.role === "full_access" ? [] : [actor.id]); return NextResponse.json({ok:true,data:result.rows.map(view)}); } catch(error){console.error("[GET /api/calendars]",error);return NextResponse.json({ok:false,error:"Không thể tải lịch."},{status:500});} }
export async function POST(request:NextRequest){try{const actor=await getSessionUser();if(!actor)return NextResponse.json({ok:false,error:"Chưa đăng nhập."},{status:401});const body=await request.json() as {id?:string;name?:string;color?:string;type?:string;visible?:boolean;ownerUserId?:string;viewerUserIds?:string[]};if(!body.id||!body.name?.trim())return NextResponse.json({ok:false,error:"Tên lịch không được để trống."},{status:400});const owner=actor.role==="full_access"&&body.ownerUserId?body.ownerUserId:actor.id;const result=await pool.query(`INSERT INTO calendars (id,name,color,owner_user_id,visible,type) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id`,[body.id,body.name.trim(),body.color||"#6366f1",owner,body.visible??true,body.type||"other"]);await syncUsers(String(result.rows[0].id),owner,actor.role==="full_access"?body.viewerUserIds||[]:[]);return NextResponse.json({ok:true},{status:201});}catch(error){console.error("[POST /api/calendars]",error);return NextResponse.json({ok:false,error:"Không thể tạo lịch."},{status:500});}}
export async function PUT(request:NextRequest){try{const actor=await getSessionUser();if(!actor)return NextResponse.json({ok:false,error:"Chưa đăng nhập."},{status:401});const body=await request.json() as {id?:string;name?:string;color?:string;type?:string;visible?:boolean;viewerUserIds?:string[]};if(!body.id||!await canEdit(actor.id,actor.role,body.id))return NextResponse.json({ok:false,error:"Không có quyền sửa lịch."},{status:403});const result=await pool.query("UPDATE calendars SET name=$2,color=$3,visible=$4,type=$5 WHERE id=$1 RETURNING owner_user_id",[body.id,body.name,body.color,body.visible??true,body.type]);if(actor.role==="full_access")await syncUsers(body.id,String(result.rows[0].owner_user_id),body.viewerUserIds||[]);return NextResponse.json({ok:true});}catch(error){console.error("[PUT /api/calendars]",error);return NextResponse.json({ok:false,error:"Không thể cập nhật lịch."},{status:500});}}
export async function DELETE(request:NextRequest){let client;try{client=await pool.connect();const actor=await getSessionUser();if(!actor)return NextResponse.json({ok:false,error:"Chưa đăng nhập."},{status:401});const id=new URL(request.url).searchParams.get("id")||"";const allowed=actor.role==="full_access"||Boolean((await client.query("SELECT 1 FROM calendars WHERE id=$1 AND owner_user_id=$2",[id,actor.id])).rows[0]);if(!id||!allowed)return NextResponse.json({ok:false,error:"Không có quyền xóa lịch."},{status:403});await client.query("BEGIN");await client.query("DELETE FROM events WHERE calendar_id=$1",[id]);await client.query("DELETE FROM calendar_users WHERE calendar_id=$1",[id]);const result=await client.query("DELETE FROM calendars WHERE id=$1 RETURNING id",[id]);if(!result.rows[0]){await client.query("ROLLBACK");return NextResponse.json({ok:false,error:"Lịch không tồn tại."},{status:404});}await client.query("COMMIT");return NextResponse.json({ok:true});}catch(error){if(client)try{await client.query("ROLLBACK");}catch(rollbackError){console.error("[DELETE /api/calendars rollback]",rollbackError);}console.error("[DELETE /api/calendars]",error);return NextResponse.json({ok:false,error:"Không thể xóa lịch."},{status:500});}finally{client?.release();}}
