-- Bổ sung liên kết thành viên và field nghiệp vụ, không xóa dữ liệu cũ.

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_date_ui DATE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority VARCHAR(16) NOT NULL DEFAULT 'normal';

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS member_id UUID;

ALTER TABLE events ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE events ADD COLUMN IF NOT EXISTS type VARCHAR(32) NOT NULL DEFAULT 'family';

ALTER TABLE notes ADD COLUMN IF NOT EXISTS member_id UUID;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS kind VARCHAR(16) NOT NULL DEFAULT 'general';
ALTER TABLE notes ADD COLUMN IF NOT EXISTS important BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS tag VARCHAR(64) NOT NULL DEFAULT '';
